/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MVenueSlugRouteImport } from './routes/m.$venueSlug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCorbeilleRouteImport } from './routes/_authenticated/admin.corbeille'
import { Route as AuthenticatedAdminVenueSlugIndexRouteImport } from './routes/_authenticated/admin.$venueSlug.index'
import { Route as AuthenticatedAdminVenueSlugCommandesRouteImport } from './routes/_authenticated/admin.$venueSlug.commandes'
import { Route as AuthenticatedAdminVenueSlugQrRouteImport } from './routes/_authenticated/admin.$venueSlug.qr'
import { Route as AuthenticatedAdminVenueSlugStockRouteImport } from './routes/_authenticated/admin.$venueSlug.stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MVenueSlugRoute = MVenueSlugRouteImport.update({
  id: '/m/$venueSlug',
  path: '/m/$venueSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCorbeilleRoute =
  AuthenticatedAdminCorbeilleRouteImport.update({
    id: '/admin/corbeille',
    path: '/admin/corbeille',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVenueSlugIndexRoute =
  AuthenticatedAdminVenueSlugIndexRouteImport.update({
    id: '/admin/$venueSlug/',
    path: '/admin/$venueSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVenueSlugCommandesRoute =
  AuthenticatedAdminVenueSlugCommandesRouteImport.update({
    id: '/admin/$venueSlug/commandes',
    path: '/admin/$venueSlug/commandes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVenueSlugQrRoute =
  AuthenticatedAdminVenueSlugQrRouteImport.update({
    id: '/admin/$venueSlug/qr',
    path: '/admin/$venueSlug/qr',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVenueSlugStockRoute =
  AuthenticatedAdminVenueSlugStockRouteImport.update({
    id: '/admin/$venueSlug/stock',
    path: '/admin/$venueSlug/stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/m/$venueSlug': typeof MVenueSlugRoute
  '/admin/corbeille': typeof AuthenticatedAdminCorbeilleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$venueSlug/commandes': typeof AuthenticatedAdminVenueSlugCommandesRoute
  '/admin/$venueSlug/qr': typeof AuthenticatedAdminVenueSlugQrRoute
  '/admin/$venueSlug/stock': typeof AuthenticatedAdminVenueSlugStockRoute
  '/admin/$venueSlug/': typeof AuthenticatedAdminVenueSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/m/$venueSlug': typeof MVenueSlugRoute
  '/admin/corbeille': typeof AuthenticatedAdminCorbeilleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$venueSlug/commandes': typeof AuthenticatedAdminVenueSlugCommandesRoute
  '/admin/$venueSlug/qr': typeof AuthenticatedAdminVenueSlugQrRoute
  '/admin/$venueSlug/stock': typeof AuthenticatedAdminVenueSlugStockRoute
  '/admin/$venueSlug': typeof AuthenticatedAdminVenueSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/m/$venueSlug': typeof MVenueSlugRoute
  '/_authenticated/admin/corbeille': typeof AuthenticatedAdminCorbeilleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$venueSlug/commandes': typeof AuthenticatedAdminVenueSlugCommandesRoute
  '/_authenticated/admin/$venueSlug/qr': typeof AuthenticatedAdminVenueSlugQrRoute
  '/_authenticated/admin/$venueSlug/stock': typeof AuthenticatedAdminVenueSlugStockRoute
  '/_authenticated/admin/$venueSlug/': typeof AuthenticatedAdminVenueSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/m/$venueSlug'
    | '/admin/corbeille'
    | '/admin/'
    | '/admin/$venueSlug/commandes'
    | '/admin/$venueSlug/qr'
    | '/admin/$venueSlug/stock'
    | '/admin/$venueSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/m/$venueSlug'
    | '/admin/corbeille'
    | '/admin'
    | '/admin/$venueSlug/commandes'
    | '/admin/$venueSlug/qr'
    | '/admin/$venueSlug/stock'
    | '/admin/$venueSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/m/$venueSlug'
    | '/_authenticated/admin/corbeille'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$venueSlug/commandes'
    | '/_authenticated/admin/$venueSlug/qr'
    | '/_authenticated/admin/$venueSlug/stock'
    | '/_authenticated/admin/$venueSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MVenueSlugRoute: typeof MVenueSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$venueSlug': {
      id: '/m/$venueSlug'
      path: '/m/$venueSlug'
      fullPath: '/m/$venueSlug'
      preLoaderRoute: typeof MVenueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/corbeille': {
      id: '/_authenticated/admin/corbeille'
      path: '/admin/corbeille'
      fullPath: '/admin/corbeille'
      preLoaderRoute: typeof AuthenticatedAdminCorbeilleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$venueSlug/': {
      id: '/_authenticated/admin/$venueSlug/'
      path: '/admin/$venueSlug'
      fullPath: '/admin/$venueSlug/'
      preLoaderRoute: typeof AuthenticatedAdminVenueSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$venueSlug/commandes': {
      id: '/_authenticated/admin/$venueSlug/commandes'
      path: '/admin/$venueSlug/commandes'
      fullPath: '/admin/$venueSlug/commandes'
      preLoaderRoute: typeof AuthenticatedAdminVenueSlugCommandesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$venueSlug/qr': {
      id: '/_authenticated/admin/$venueSlug/qr'
      path: '/admin/$venueSlug/qr'
      fullPath: '/admin/$venueSlug/qr'
      preLoaderRoute: typeof AuthenticatedAdminVenueSlugQrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$venueSlug/stock': {
      id: '/_authenticated/admin/$venueSlug/stock'
      path: '/admin/$venueSlug/stock'
      fullPath: '/admin/$venueSlug/stock'
      preLoaderRoute: typeof AuthenticatedAdminVenueSlugStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminCorbeilleRoute: typeof AuthenticatedAdminCorbeilleRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminVenueSlugCommandesRoute: typeof AuthenticatedAdminVenueSlugCommandesRoute
  AuthenticatedAdminVenueSlugQrRoute: typeof AuthenticatedAdminVenueSlugQrRoute
  AuthenticatedAdminVenueSlugStockRoute: typeof AuthenticatedAdminVenueSlugStockRoute
  AuthenticatedAdminVenueSlugIndexRoute: typeof AuthenticatedAdminVenueSlugIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminCorbeilleRoute: AuthenticatedAdminCorbeilleRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminVenueSlugCommandesRoute:
    AuthenticatedAdminVenueSlugCommandesRoute,
  AuthenticatedAdminVenueSlugQrRoute: AuthenticatedAdminVenueSlugQrRoute,
  AuthenticatedAdminVenueSlugStockRoute: AuthenticatedAdminVenueSlugStockRoute,
  AuthenticatedAdminVenueSlugIndexRoute: AuthenticatedAdminVenueSlugIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MVenueSlugRoute: MVenueSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
